import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/Components/Sidebar";
import ProfileButton from "@/Components/ProfileButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Story Quest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="absolute top-0 right-56 m-0 p-0">
            <ProfileButton />
        </div>
        <div className="w-full h-full flex flex-row">
          <Sidebar></Sidebar>
          {children}
        </div>
      </body>
    </html>
  );
}
